const userExtractMockData = [
  {
    extract_id: 4,
    description: 'TEST DDSTD',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '09/26/2018 16:10',
    created_by: 'ca31453',
    updated_on: '08/30/2021 18:55',
    updated_by: 'DELTADS/ca31453',
    file_layout: 'ADP',
    groups: '03272',
    divisions: '',
    tpa_name: '',
  },
  {
    extract_id: 22,
    description: 'DDSTD GRP 03',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/27/2018 15:40',
    created_by: 'ca31453',
    updated_on: '10/09/2019 10:20',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '03272',
    divisions: '00001',
    tpa_name: '',
  },
  {
    extract_id: 23,
    description: 'DDSTD GRP 03',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/28/2018 15:10',
    created_by: 'ca31453',
    updated_on: '11/28/2018 22:40',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '03272',
    divisions: '',
    tpa_name: 'AON HEWITT/T',
  },
  {
    extract_id: 24,
    description: 'DDSTD GRP 03',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/29/2018 23:50',
    created_by: 'ca31453',
    updated_on: '08/30/2021 18:55',
    updated_by: 'DELTADS/ca31453',
    file_layout: 'ADP',
    groups: '03272',
    divisions: '00013,00023',
    tpa_name: '',
  },
  {
    extract_id: 25,
    description: 'Multi Group Set',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/30/2018 02:05',
    created_by: 'ca31453',
    updated_on: '02/04/2020 16:10',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '01005,01006',
    divisions: '',
    tpa_name: 'HEALTH ADVO',
  },
  {
    extract_id: 30,
    description: 'Extract for03272',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'N',
    created_on: '12/04/2018 10:50',
    created_by: 'ca31453',
    updated_on: '',
    updated_by: '',
    file_layout: 'DDSTD',
    groups: '15577',
    divisions: '',
    tpa_name: 'AONHEWIT',
  },
  {
    extract_id: 31,
    description: 'Coca-Cola Extract',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'N',
    created_on: '12/04/2018 11:00',
    created_by: 'ga28828',
    updated_on: '12/04/2018 11:07',
    updated_by: 'ga28828',
    file_layout: 'DDSTD',
    groups: '15986',
    divisions: '',
    tpa_name: 'HEALTH EQUITY',
  },
  {
    extract_id: 32,
    description: 'abc',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'N',
    created_on: '12/04/2018 14:10',
    created_by: 'DELTADS/ca59',
    updated_on: '01/09/2019 16:10',
    updated_by: 'CA60510',
    file_layout: 'Aetna',
    groups: '03272',
    divisions: '',
    tpa_name: '',
  },
  {
    extract_id: 33,
    description: 'Coca-Cola Extract',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '12/05/2018 10:40',
    created_by: 'ca31453',
    updated_on: '12/05/2018 10:50',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '15986',
    divisions: '',
    tpa_name: 'HEALTH EQUITY',
  },
];

const userSheduleRosterMockData = [
  {
    shedule_id: 1,
    extract_id: 4,
    description: 'TEST DDSTD',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '09/26/2018 16:10',
    created_by: 'ca31453',
    updated_on: '08/30/2021 18:55',
    updated_by: 'DELTADS/ca31453',
    file_layout: 'ADP',
    groups: '03272',
    divisions: '',
    tpa_name: '',
  },
  {
    shedule_id: 2,
    extract_id: 22,
    description: 'DDSTD GRP 03',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/27/2018 15:40',
    created_by: 'ca31453',
    updated_on: '10/09/2019 10:20',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '03272',
    divisions: '00001',
    tpa_name: '',
  },
  {
    shedule_id: 3,
    extract_id: 23,
    description: 'DDSTD GRP 03',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/28/2018 15:10',
    created_by: 'ca31453',
    updated_on: '11/28/2018 22:40',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '03272',
    divisions: '',
    tpa_name: 'AON HEWITT/T',
  },
  {
    shedule_id: 4,
    extract_id: 24,
    description: 'DDSTD GRP 03',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/29/2018 23:50',
    created_by: 'ca31453',
    updated_on: '08/30/2021 18:55',
    updated_by: 'DELTADS/ca31453',
    file_layout: 'ADP',
    groups: '03272',
    divisions: '00013,00023',
    tpa_name: '',
  },
  {
    shedule_id: 5,
    extract_id: 25,
    description: 'Multi Group Set',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '11/30/2018 02:05',
    created_by: 'ca31453',
    updated_on: '02/04/2020 16:10',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '01005,01006',
    divisions: '',
    tpa_name: 'HEALTH ADVO',
  },
  {
    shedule_id: 6,
    extract_id: 30,
    description: 'Extract for03272',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'N',
    created_on: '12/04/2018 10:50',
    created_by: 'ca31453',
    updated_on: '',
    updated_by: '',
    file_layout: 'DDSTD',
    groups: '15577',
    divisions: '',
    tpa_name: 'AONHEWIT',
  },
  {
    shedule_id: 7,
    extract_id: 31,
    description: 'Coca-Cola Extract',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'N',
    created_on: '12/04/2018 11:00',
    created_by: 'ga28828',
    updated_on: '12/04/2018 11:07',
    updated_by: 'ga28828',
    file_layout: 'DDSTD',
    groups: '15986',
    divisions: '',
    tpa_name: 'HEALTH EQUITY',
  },
  {
    shedule_id: 8,
    extract_id: 32,
    description: 'abc',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'N',
    created_on: '12/04/2018 14:10',
    created_by: 'DELTADS/ca59',
    updated_on: '01/09/2019 16:10',
    updated_by: 'CA60510',
    file_layout: 'Aetna',
    groups: '03272',
    divisions: '',
    tpa_name: '',
  },
  {
    shedule_id: 9,
    extract_id: 33,
    description: 'Coca-Cola Extract',
    interface_ID: 'IF145',
    active_status: 'active',
    shedule_status: 'Y',
    created_on: '12/05/2018 10:40',
    created_by: 'ca31453',
    updated_on: '12/05/2018 10:50',
    updated_by: 'ca31453',
    file_layout: 'DDSTD',
    groups: '15986',
    divisions: '',
    tpa_name: 'HEALTH EQUITY',
  },
];

const transmissionHistoryMockData = [
  {
    extract_id: 501,
    transmission_date: '06/12/2020 ...',
    action: 'MOVED',
    source_name: 'IF145E_PayFlex_043324.psv',
    destination_host: 'PayFlex (Summit Funding ...',
    destination_name: '/DELTA_CLAIMS/FLEX/IN...',
    size: '26743',
    result: '0',
    message: '',
  },
  {
    extract_id: 413,
    transmission_date: '06/12/2020 ...',
    action: 'MOVED',
    source_name: 'IF145E_PayFlex_043324.psv',
    destination_host: 'PayFlex (Summit Funding ...',
    destination_name: '/DELTA_CLAIMS/FLEX/IN...',
    size: '26743',
    result: '0',
    message: '',
  },
  {
    extract_id: 4154,
    transmission_date: '06/12/2020 ...',
    action: 'MOVED',
    source_name: 'IF145E_PayFlex_043324.psv',
    destination_host: 'PayFlex (Summit Funding ...',
    destination_name: '/DELTA_CLAIMS/FLEX/IN...',
    size: '26743',
    result: '0',
    message: '',
  },
  {
    extract_id: 417,
    transmission_date: '06/12/2020 ...',
    action: 'MOVED',
    source_name: 'IF145E_PayFlex_043324.psv',
    destination_host: 'PayFlex (Summit Funding ...',
    destination_name: '/DELTA_CLAIMS/FLEX/IN...',
    size: '26743',
    result: '0',
    message: '',
  },
  {
    extract_id: 417,
    transmission_date: '06/12/2020 ...',
    action: 'MOVED',
    source_name: 'IF145E_PayFlex_043324.psv',
    destination_host: 'PayFlex (Summit Funding ...',
    destination_name: '/DELTA_CLAIMS/FLEX/IN...',
    size: '26743',
    result: '0',
    message: '',
  },
  {
    extract_id: 4143,
    transmission_date: '06/12/2020 ...',
    action: 'MOVED',
    source_name: 'IF145E_PayFlex_043324.psv',
    destination_host: 'PayFlex (Summit Funding ...',
    destination_name: '/DELTA_CLAIMS/FLEX/IN...',
    size: '26743',
    result: '0',
    message: '',
  },
];

const newExtractsModalField = [
  {
    file_layout_id: '150_Byte_with_...',
    file_layout_description: 'FSA-150_Byte...',
  },
  {
    file_layout_id: 'ADP',
    file_layout_description: 'FSA-ADP_800...',
  },
  {
    file_layout_id: '150_Byte_with_...',
    file_layout_description: 'FSA-150_Byte...',
  },
  {
    file_layout_id: 'ADP',
    file_layout_description: 'FSA-ADP_800...',
  },
  {
    file_layout_id: '150_Byte_with_...',
    file_layout_description: 'FSA-150_Byte...',
  },
  {
    file_layout_id: 'ADP',
    file_layout_description: 'FSA-ADP_800...',
  },
  {
    file_layout_id: '150_Byte_with_...',
    file_layout_description: 'FSA-150_Byte...',
  },
  {
    file_layout_id: 'ADP',
    file_layout_description: 'FSA-ADP_800...',
  },
];

const extractParameters = [
  {
    extract_parameter_id: 1,
    extract_parameter_name: 'FROM_GROUP',
    extract_parameter_description: 'MTV group number',
    extract_parameter_data_type: 'VARCHAR',
    extract_parameter_data_length: 5,
    extract_parameter_hint: 'Group(numbers ...)',
    created_on: '1/14/2010',
    created_by: 'CAE0005',
    updated_on: '1/14/2010',
    updated_by: 'CAE0005',
  },
  {
    extract_parameter_id: 2,
    extract_parameter_name: 'THRU_GROUP',
    extract_parameter_description: 'MTV group number',
    extract_parameter_data_type: 'VARCHAR',
    extract_parameter_data_length: 5,
    extract_parameter_hint: 'Group(numbers ...)',
    created_on: '1/14/2010',
    created_by: 'CAE0005',
    updated_on: '1/14/2010',
    updated_by: 'CAE0005',
  },
  {
    extract_parameter_id: 3,
    extract_parameter_name: 'FROM_GROUP',
    extract_parameter_description: 'MTV group number',
    extract_parameter_data_type: 'VARCHAR',
    extract_parameter_data_length: 5,
    extract_parameter_hint: 'Group(numbers ...)',
    created_on: '1/14/2010',
    created_by: 'CAE0005',
    updated_on: '1/14/2010',
    updated_by: 'CAE0005',
  },
  {
    extract_parameter_id: 4,
    extract_parameter_name: 'FROM_GROUP',
    extract_parameter_description: 'MTV group number',
    extract_parameter_data_type: 'VARCHAR',
    extract_parameter_data_length: 5,
    extract_parameter_hint: 'Group(numbers ...)',
    created_on: '1/14/2010',
    created_by: 'CAE0005',
    updated_on: '1/14/2010',
    updated_by: 'CAE0005',
  },
  {
    extract_parameter_id: 5,
    extract_parameter_name: 'FROM_GROUP',
    extract_parameter_description: 'MTV group number',
    extract_parameter_data_type: 'VARCHAR',
    extract_parameter_data_length: 5,
    extract_parameter_hint: 'Group(numbers ...)',
    created_on: '1/14/2010',
    created_by: 'CAE0005',
    updated_on: '1/14/2010',
    updated_by: 'CAE0005',
  },
];

const defaultFileLayoutParameters = [
  {
    label: 'SHOW_CDT_CD',
    selected: false,
  },
  {
    label: 'SHOW_COLUMN_HEADER',
    selected: false,
  },
  {
    label: 'SHOW_GENDER',
    selected: false,
  },
  {
    label: 'SHOW_INCENTIVE_COUNT',
    selected: false,
  },
  {
    label: 'SHOW_LIABILITY_INDICATOR',
    selected: false,
  },
  {
    label: 'SUBSCRIBER_ID2_TYPE',
    selected: true,
  },
  {
    label: 'SUBSCRIBER_ID2_TYPE',
    selected: false,
  },
  {
    label: 'TTPA_ID',
    selected: true,
  },
  {
    label: 'TPA_NAME',
    selected: false,
  },
];

const listOfValuesMockData = [
  {
    id: 23455,
    description: 'FSA-150-DAPP-LSLAL',
  },
  {
    id: 23452315,
    description: 'FSA-150-DAPP-LSLAL-SAKD',
  },
  {
    id: 23455,
    description: 'FSA-150-DAPP-LSLAL',
  },
  {
    id: 23452315,
    description: 'FSA-150-DAPP-LSLAL-SAKD',
  },
  {
    id: 23455,
    description: 'FSA-150-DAPP-LSLAL',
  },
  {
    id: 23452315,
    description: 'FSA-150-DAPP-LSLAL-SAKD',
  },
  {
    id: 23455,
    description: 'FSA-150-DAPP-LSLAL',
  },
  {
    id: 23452315,
    description: 'FSA-150-DAPP-LSLAL-SAKD',
  },
  {
    id: 23455,
    description: 'FSA-150-DAPP-LSLAL',
  },
  {
    id: 23452315,
    description: 'FSA-150-DAPP-LSLAL-SAKD',
  },
];

export const transmissionHistoryData = JSON.stringify(transmissionHistoryMockData);
export const usersSheduleRosterData = JSON.stringify(userSheduleRosterMockData);
export const usersExtractData = JSON.stringify(userExtractMockData);
export const newExtractModalField = JSON.stringify(newExtractsModalField);
export const extractParametersData = JSON.stringify(extractParameters);
export const defaultFileLayoutParametersData = JSON.stringify(defaultFileLayoutParameters);
export const defaultListOfValuesMockData = JSON.stringify(listOfValuesMockData);
